### ISSUE TITLE
Update `update_inspection` function to reflect `verified` attribute change

### ISSUE THREAD

**Issue by k-allagbe** [ai-cfia/ailab-datastore#119]
## Description

In reference to https://github.com/ai-cfia/ailab-datastore/pull/103, the `verified` attribute has been moved from the `ProductInformation` model to the `Inspection` base model. The `update_inspection` function must be updated to accommodate this change.

**Comment by Francois-Werbrouck** [comment]
There also is the "id" variable that has been switched to "inspection_id"
