### ISSUE TITLE
Create a Function for Container Name Creation Logic

### ISSUE THREAD

**Issue by k-allagbe** [ai-cfia/ailab-datastore#137]
## Description
Currently, the logic to create blob container names is scattered throughout the codebase using the following pattern:

```
container_name = "{}-{}".format(tier, container_uuid)
```
or a similar variation like:
```
container_name = f"{tier}-{user_uuid}"
```
This repetitive code can lead to inconsistencies and maintenance difficulties. To address this, we should refactor the logic into a dedicated function that can be reused across the codebase.

## Tasks
- Implement a function that encapsulates the logic for creating blob container names.
- Refactor all existing code to replace instances of `container_name = "{}-{}".format(tier, container_uuid)` and similar patterns with calls to the new function.
- Place the function in a module where it can be easily accessed by other parts of the codebase.
- Write unit tests for the new function to ensure it behaves correctly.
- Ensure all tests pass after making these changes.

**Comment by Francois-Werbrouck** [comment]
>Place the function in a module where it can be easily accessed by other parts of the codebase.

I placed the f() in 📦 `datastore/blob/azure_storage_api`. This way, it is easily reachable by the codebase (most calls should come from within this module.)

**Comment by Francois-Werbrouck** [comment]
FYI: I also included a `build_blob_name()` which wasn't in the scope of this issue, but seemed to follow the same idea
