### ISSUE TITLE
Guaranteed analysis title in `fertiscan`

### ISSUE THREAD

**Issue by k-allagbe** [ai-cfia/ailab-datastore#149]
As requested, we need to add a new field in the schema to describe the title of the guaranteed analysis.

![image](https://github.com/user-attachments/assets/7fdf5722-c711-4295-a90d-017e68cc0ae5)

Verbatim quote: "Le titre est important puisque selon que "minimal" apparaît ou pas, les termes utilisés pour les éléments nutritifs vont changés aussi."

**Comment by k-allagbe** [comment]
I suggest naming the field `type` or `guaranteed_analysis_type` depending of where it should be placed.

**Comment by Francois-Werbrouck** [comment]
Based on the Backend, we will assume the new `input_json` looks like the following: 

```JSON
{
  "company_name": "GreenGrow Inc.",
  "company_address": "123 Green Road, Farmville, State, 12345",
  "company_website": "https://www.greengrow.com",
  "company_phone_number": "123-456-7890",
  "manufacturer_name": "AgriSupply Co.",
  "manufacturer_address": "456 Supply Lane, AgriTown, State, 67890",
  "manufacturer_website": "https://www.agrisupply.com",
  "manufacturer_phone_number": "987-654-3210",
  "fertiliser_name": "GreenGrow Fertilizer 20-20-20",
  "registration_number": "FG123456",
  "lot_number": "LOT20240901",
  "weight": [
    {
      "value": "50",
      "unit": "kg"
    }
  ],
  "density": {
    "value": "1.5",
    "unit": "g/cm³"
  },
  "volume": {
    "value": "33.3",
    "unit": "L"
  },
  "npk": "20-20-20",
  "guaranteed_analysis_en": {
    "title": "Guaranteed Analysis",
    "nutrients": [
      {
        "nutrient": "Total Nitrogen (N)",
        "value": "20",
        "unit": "%"
      },
      {
        "nutrient": "Available Phosphate (P2O5)",
        "value": "20",
        "unit": "%"
      },
      {
        "nutrient": "Soluble Potash (K2O)",
        "value": "20",
        "unit": "%"
      }
    ]
  },
  "guaranteed_analysis_fr": {
    "title": "Analyse Garantie",
    "nutrients": [
      {
        "nutrient": "Azote total (N)",
        "value": "20",
        "unit": "%"
      },
      {
        "nutrient": "Phosphate assimilable (P2O5)",
        "value": "20",
        "unit": "%"
      },
      {
        "nutrient": "Potasse soluble (K2O)",
        "value": "20",
        "unit": "%"
      }
    ]
  },
  "cautions_en": [
    "Keep out of reach of children.",
    "Store in a cool, dry place."
  ],
  "cautions_fr": [
    "Garder hors de la portée des enfants.",
    "Conserver dans un endroit frais et sec."
  ],
  "instructions_en": [
    "Apply evenly across the field at a rate of 5 kg per hectare.",
    "Water thoroughly after application."
  ],
  "instructions_fr": [
    "Appliquer uniformément sur le champ à raison de 5 kg par hectare.",
    "Arroser abondamment après l'application."
  ]
}
```

**Comment by k-allagbe** [comment]
Will build_inspection_export and update_inspection be impacted too?

I suggest breaking these into atomic more manageable issues to avoid thousand lines PRs.

**Comment by Francois-Werbrouck** [comment]
> Will build_inspection_export and update_inspection be impacted too?

Yes, added it into the TODO
> I suggest breaking these into atomic more manageable issues to avoid thousand lines PRs.

The Epic is already separated into multiple issues. This issue is about only the title, making it into multiple issues doesn't seem to really work since some tests wont pass. EG: If i do an issue for the insert, the update might be broken, and the workflow wont pass.

I rather have everything about the title into one issue. 
I already duplicate my work into multiple issue which mean I will need to update the schema/insert/update/getter multiple time for each changes we've identified in the epic. It would be easier for me to integrate everything into one PR to streamline my work, but for reviewing I will spread it across multiple PR for each changes as you've planned. It is normal to have a thousand line rework since this issue affect us all across the datastore.

Maybe next time, we want want to have less big PR we could try to cut the Epics based on the datastore operations and not for each changes?

**Comment by k-allagbe** [comment]
There is the option of commenting tests that might be affected. But I agree, if these are tightly coupled, better not merge pieces that would break functionalities on their own.

**Comment by Francois-Werbrouck** [comment]
> I suggest breaking these into atomic more manageable issues to avoid thousand lines PRs.

Before working on the tests here are the changes: 
![image](https://github.com/user-attachments/assets/f440668f-2690-4625-9616-383427f2de4c)

**Comment by Francois-Werbrouck** [comment]
After working on tests: 
![{94E89234-9468-432C-90B3-70E99DF7F0A3}](https://github.com/user-attachments/assets/c6016f81-0d48-4a5a-bf9e-411c9d1fe376)

**Comment by Francois-Werbrouck** [comment]
It seems there is a test not passing in the coverage? I will look into it later, but other than that this PR is ready for review. However we will wait until #112 to merge it into main

**Comment by k-allagbe** [comment]
Closing this as completed in #171.
