### ISSUE TITLE
As an inspector, I want to store record_keeping options in `fertiscan`

### ISSUE THREAD

**Issue by k-allagbe** [ai-cfia/ailab-datastore#150]
## Description

**Context**  
We need to implement a new labelling option field as discussed with the main user. The field will provide two options: record keeping (tenue de document) and no record keeping. Record keeping refers to a legal practice where the manufacturer chooses not to disclose publicly the list of active ingredients. Instead, the label will indicate: "Active ingredients derived from registered and exempt materials". If record keeping is not chosen, the active ingredients will be listed on the label as usual.

**Problem Statement**  
The datastore currently does not support a way to track or store the labelling option for record keeping. This feature needs to be added to the system, ensuring that it is properly stored. The developer should assess how this change impacts the database schema, determine the necessary adjustments and propose updates to the inspection data format.

**Acceptance Criteria**  
- A labelling option for record keeping and no record keeping must be added to the datastore.
- The information must be stored correctly during creation and update, ensuring proper retrieval.
- Investigate whether the database schema requires updates based on the new labelling option.
- propose updates to the inspection data format

**Additional Information** 
- ref: https://github.com/ai-cfia/fertiscan-pipeline/issues/28
- Example of legal record keeping PDF: [Tenue de documentation.PDF](https://github.com/user-attachments/files/16949972/Tenue.de.documentation.PDF)  
- Additional info: [https://inspection.canada.ca/en/plant-health/fertilizers/trade-memoranda/t-4-131](https://inspection.canada.ca/en/plant-health/fertilizers/trade-memoranda/t-4-131)
- post update to the inspection data format here: https://github.com/ai-cfia/fertiscan-frontend/issues/229

**Comment by Francois-Werbrouck** [comment]
This issue is too vague and we need to sit down and really think how we plan on retrieving this kind of data with the Backend and how we want to return it.

**Comment by k-allagbe** [comment]
> This issue is too vague and we need to sit down and really think how we plan on retrieving this kind of data with the Backend and how we want to return it.

Updated. Please concert with @Youllou on the inspection data format.

**Comment by Francois-Werbrouck** [comment]
can the new data format be included in the Issue? @k-allagbe @Youllou.
Also, do we pick in the pipeline if it is a `record keeping` case? 
If not, I advise we wait until all the changes picked from the pipeline are implemented before implementing these changes to avoid conflicts and problems.

**Comment by Francois-Werbrouck** [comment]
Also this is not a `as a dev` issue since these changes are part of a user's need. @k-allagbe Can we make an Epic with all the requiered documentation to implement the changes?

**Comment by k-allagbe** [comment]
> Do we pick in the pipeline if it is a `record keeping` case? If not, I advise we wait until all the changes picked from the pipeline are implemented before implementing these changes to avoid conflicts and problems.

Please, have a chat with @snakedye and @Endlessflow. A discussion in teams would be great.

> Also this is not a `as a dev` issue since these changes are part of a user's need. @k-allagbe Can we make an Epic with all the requiered documentation to implement the changes?

Done. If some are missing, please feel free to update the epic.

**Comment by Francois-Werbrouck** [comment]
I've currently halted the work for the 📦 `fertiscan.metadata.inspection.build_inspection_import()` and asked the team how we should proceed regarding displaying the content of the fertilizer if it is a record_keeping label

```python
        # Get the guaranteed analysis
        if product_info.record_keeping != True:
            guaranteed_analysis = nutrients.get_guaranteed_analysis_json(
                cursor, label_info_id
            )
        else:
            print("Record keeping is true")
            raise BuildInspectionExportError("Record keeping is true")
        guaranteed_analysis = GuaranteedAnalysis.model_validate(guaranteed_analysis)
```
