### ISSUE TITLE
As a dev, I want to store inspector notes and comments in `fertiscan`

### ISSUE THREAD

**Issue by k-allagbe** [ai-cfia/ailab-datastore#151]
## Description

**Context**  
After discussions with our main user, we decided to delay the allegation implementation to a later iteration due to the time needed for research. In the meantime, inspectors need the ability to input notes and comments during their inspections.

**Problem Statement**  
There is no current provision in the database to store inspector notes/comments.

**Acceptance Criteria**  
- Notes/comments are stored.
- Each note/comment must be associated with the correct inspection and inspector.
- The data is retrievable for display when reviewing or revisiting inspections.
  
**Additional Information**
- Post update to the inspection data format here: https://github.com/ai-cfia/fertiscan-frontend/issues/229

**Comment by Francois-Werbrouck** [comment]
Inspection updated with a field for the comment:

```JSON
{
  "inspection_id": "uuid",
  "inspection_comment": "some comment/ user feedback in text",
  "verified": false,
  "product": {
...
```

**Comment by k-allagbe** [comment]
Closing this as completed in #171.
