### ISSUE TITLE
As an Inpector, I want to store all registration numbers

### ISSUE THREAD

**Issue by k-allagbe** [ai-cfia/ailab-datastore#154]
## Description
Inspectors rely on the presence of registration numbers. A Reg Number can either represent the fertilizer or an ingredient in the fertilizers to ensure compliance with regulatory standards. If a registered ingredient is used, the registration number must be listed by the manufacturer. Currently, the system does not scan and store this information nor does it pick up multiple Reg Numbers

**Acceptance Criteria**
- Ensure the database can store multiple registration number
- Any updates made by inspectors to the registration number must be saved and retrievable.
- Ensure the changes are tested

**Additional Information**
- ref: https://github.com/ai-cfia/fertiscan-pipeline/issues/30
- post updates to the inspection data format here: https://github.com/ai-cfia/fertiscan-frontend/issues/229

**Comment by Francois-Werbrouck** [comment]
Didn't we dropped the ingredients from our schema?

**Comment by k-allagbe** [comment]
> Didn't we dropped the ingredients from our schema? I asked a question in the related issue to this one about if its related to the guaranteed_analysis nutrients.

Ingredients will be extracted.

> I also advise instead of creating an issue in the datastore and doing exactly what's asked from the client, we should dig deeper. 

We did. These are the issues that came out of all the talks with the client. If there is something specific you'd like to clarify, please open a thread on teams with the client. I'll track it for you in your off days.

> There is already a table for all element_compound. If this issue true is a necessity and they want to keep track of registered ingredient/Guaranteed_analysis nutrient, we should require our client to produce/verify a listing and give us extra details on the specifics of the ingredients like previously discussed during the team revision.

That would certainly help pipeline devs. Is that relevant for the datastore though? 
Here's an example:
![image](https://github.com/user-attachments/assets/2fab12b6-0fb5-4cce-abdb-2ba7b22099d4)

**Comment by Francois-Werbrouck** [comment]
This issue has been reviewed and updated based on the client's needs
