### ISSUE TITLE
As a dev, I want to adapt the `build_inspection_import` function to the new analysis data format in `fertiscan`

### ISSUE THREAD

**Issue by k-allagbe** [ai-cfia/ailab-datastore#161]
## Description  

The `build_inspection_import` function in the datastore is currently tailored to an outdated format of the fertilizer label analysis. However, a new format for the fertilizer label analysis has been introduced, requiring an update to ensure proper data handling and compliance with the new structure. The goal is to update the function to handle this new JSON format.

**Acceptance Criteria**  
- Update the `build_inspection_import` function to parse the new fertilizer label analysis JSON format.
- Ensure backward compatibility, so old data formats are still processed correctly if necessary.
- Test cases are provided or updated to reflect the changes in the function and ensure both old and new formats are handled accurately.

**Additional Information**
- ref: Additional information section of https://github.com/ai-cfia/fertiscan-frontend/issues/229

**Comment by Francois-Werbrouck** [comment]
I'm sorry but this is already done in #149

**Comment by k-allagbe** [comment]
Closing this as done in #171.
