### ISSUE TITLE
As a dev, I want the correct return type specified in the `register_user` function

### ISSUE THREAD

**Issue by k-allagbe** [ai-cfia/ailab-datastore#201]
## Description  

**Context**  
In the core datastore, we have a function `register_user` that registers a user in the database. The function currently has a return type annotation of `None`, but it returns the UUID of the user after successful registration.

**Problem Statement**  
The return type of `register_user` is incorrectly specified as `None`. Since the function actually returns the UUID of the newly registered user, the return type should reflect this to avoid confusion and ensure proper typing.

## Acceptance Criteria  
- Update the return type annotation of `register_user` to match the actual return value.
- Ensure that the function is correctly typed to return a `UUID` or `str`, depending on how the UUID is represented in the database.

**Comment by Francois-Werbrouck** [comment]
This is not a Fertiscan Issue, moved it

**Comment by Francois-Werbrouck** [comment]
This issue was addressed in another PR, therefore I'm linking it and there should be no work to be done here
