### ISSUE TITLE
Read a fertiscan inspection by id

### ISSUE THREAD

**Issue by k-allagbe** [ai-cfia/ailab-datastore#83]
This is in direct continuation of #77.

Provided an id, the datastore must return the corresponding label information in the format described in #77.

**Comment by Francois-Werbrouck** [comment]
https://github.com/ai-cfia/ailab-datastore/issues/96

**Comment by k-allagbe** [comment]
Duplicate of https://github.com/ai-cfia/ailab-datastore/issues/93. Is done in #96. Closing this.
